version: "3"
services:
    back:
        build: ./railsback
        restart: always
        env_file:
            - ./secrets.env
        environment:
            - RAILS_ENV=production
            - FRONT_ADDR=front
            - DATABASE_URL=postgres://postgres@db/black_book_production
        depends_on:
            - db
    front:
        build: ./nuxtfront
        restart: always
        ports:
            - "80:3000"
        environment:
            - API_URL=http://back:3000/api/
            - NODE_ENV=production
            - NODE_CONFIG_PRODUCTION=false
    db:
        image: postgres:12
        restart: always
        env_file:
            - ./secrets.env
        volumes:
            - "black_book_data:/var/lib/postgresql/data"
volumes:
    black_book_data:
